[site]
title = "Like Liu"
description = "Undergraduate student in Software Engineering at Northwestern Polytechnical University."
favicon = "/favicon.svg"
last_updated = "November 27, 2025"

[author]
name = "Like Liu"
category = "BEng in Software Engineering"
school = "School of Software"
university = "Northwestern Polytechnical University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "like.liu@mail.nwpu.edu.cn"
location = "Xi'an, China"
location_url = "https://j.map.baidu.com/25/ish"
location_details = [
  "Northwestern Polytechnical University,",
  "Xi'an, Shaanxi, China"
]
google_scholar = ""
orcid = ""
github = "https://github.com/Lozumi"
linkedin = ""

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "Homepage"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Practices"
type = "page"
target = "practices"
href = "/practices"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
