
[[news]]
date = "2025-11"
content = "One paper has been accepted by AAAI 2026 ğŸ“"

[[news]]
date = "2025-08"
content = "One paper has been accepted by ICAUS 2025 ğŸ“"

[[news]]
date = "2025-02"
content = "Started new research project on Zero-shot UAV Vision-and-Language Navigation"

[[news]]
date = "2024-11"
content = "Started new research project on Fine-grained Action Recognition"

[[news]]
date = "2024-11"
content = "Attended COP29 as NPU Student Representative in Baku, Azerbaijan ğŸŒ"

[[news]]
date = "2024-11"
content = "Won Second Prize in Challenge Cup 2024 ğŸ†"

[[news]]
date = "2024-08"
content = "Completed internship at QingCloud Technology as AI Development Engineer"
